# Setup your replica count!
autoscaling:
  enabled: true
  minReplicas:
    ui: 1
    api: 1
    notification: 0
    poller: 0

limitRange:
  enabled: true
  limits:
    - max:
        cpu: '1'
        memory: 2Gi
      default:
        cpu: '1'
        memory: 2Gi
      defaultRequest:
        cpu: '1'
        memory: 2Gi
      type: Container


# Where are your images?
image:
  repository: localhost:5000/qtestmgr
  liquibase: localhost:5000/liquibase
  pullPolicy: IfNotPresent
  tag: latest
  liquibasetag: latest

# Setup Ingress with TLS
secrets:
  enabled: true

# Your desktop doesn't have an LB
service:
  type: ClusterIP

### Ingress/IngressClass (> K8s 1.18-1.22+) #####
ingressClass:
  enabled: true
  labels: {}
  controller: k8s.io/ingress-nginx
  isDefaultClass: true
  # Use to force a networking.k8s.io API Version for certain CI/CD applications. Ex. "v1"
  fallbackApiVersion: ""

ingress:
  enabled: true
  name: qtest-insights-ingress
  labels: {}
  annotations: {}
  canary:
    annotationPrefix: ""
    annotations: 
     ingress.kubernetes.io/rewrite-target: /
      # canary-by-header: []
      # canary-by-header-pattern: []
  hosts:
     - nephele.qtest.local
     - qtestdev1.qtest.local

  paths: []

  extraPaths:
    - path: /*
      pathType: ImplementationSpecific
secrets:
  enabled: true
  tls:
    []
    # - secretName: qtest-svc-tls
    #   hosts:
    #     - svc.qtest.com
  https: false

# qTest Manager
qTestManager:
  client:
    jdbc:
      postgresUrl: jdbc:postgresql://host.docker.internal/qTest
      postgresUserName: postgres
      postgresPassword: cG9zdGdyZXM=
      postgresReadOnlyUrl: jdbc:postgresql://host.docker.internal/qTest
      postgresReadOnlyUserName: postgres
      postgresReadOnlyPassword: cG9zdGdyZXM=
  notification:
    urlExternal: https://nephele.qtest.local
  preUrl: http://<sitename>.qtest.local
  preUrlHttps: https://<sitename>.qtest.local
  attachmentFolderPath: /mnt/data/qtest/attachments
  licenseFolderPath: /mnt/data/qtest/license

# Turn off persistence
persistence:
  enabled: false

testconductor:
  environment:
    isOnPremise: true
secrets:
  enabled: true
# HPA values
autoscaling:
  enabled: true
  minReplicas:
    ui: 1
    api: 1
    notification: 1
    poller: 1
    default: 1
  maxReplicas:
    ui: 3
    api: 3
    notification: 3
    poller: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
  healthApiPath: /health-checker
